apiVersion: v1
kind: Secret
metadata:
  name: jfrog-credlogin
  namespace: taxi02
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDIuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImNtRjJhVHBMWVc1a1lXZGhaR3hoT1RFayIKCQl9LAoJCSJ0cmlhbGhsMG9nMS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiY21GMmFUcExZVzVrWVdkaFpHeGhPVEVrIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson