apiVersion: v1
kind: Service
metadata:
  name:  taxi-booking-service
  namespace: taxi02
spec:
  type: LoadBalancer
  selector:
    app: taxi-booking
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8080